//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Data()
        {
            this.Comment = new HashSet<Comment>();
        }
    
        public string dataID { get; set; }
        public string dataTitle { get; set; }
        public string dataDesc { get; set; }
        public string dataCategory { get; set; }
        public string dataImgUrl { get; set; }
        public string dataCreatorID { get; set; }
        public int dataLikeCount { get; set; }
        public int dataCommentCount { get; set; }
        public string dataLikes { get; set; }
        public string dataComments { get; set; }
        public int dataCreateDate { get; set; }
        public string dataCreatorName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
    }
}
